# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/14 12:31:59 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Variables
SUBDIR	:=	ctype
NAME	:=	ctype.a
SRC		:=	src/ft_isalnum.c \
			src/ft_isascii.c \
			src/ft_iscntrl.c \
			src/ft_isgraph.c \
			src/ft_isprint.c \
			src/ft_isspace.c \
			src/ft_isxdigit.c \
			src/ft_toupper.c \
			src/ft_isalpha.c \
			src/ft_isblank.c \
			src/ft_isdigit.c \
			src/ft_islower.c \
			src/ft_ispunct.c \
			src/ft_isupper.c \
			src/ft_tolower.c

TEST	:=	test/ft_ctype_test.c
INCLUDE	+=	-Iinclude

include	../makeconfig
