# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/14 16:45:55 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Variables
SUBDIR	:=	ft_stdio
NAME	:=	ft_stdio.a
SRC		:=	src/ft_printf_utils/ft_utils.c \
			src/ft_printf_utils/ft_utils_strjoin.c \
			src/ft_printf_utils/ft_handle/ft_conv_info_handle.c \
			src/ft_printf_utils/ft_handle/ft_handle_char.c \
			src/ft_printf_utils/ft_handle/ft_handle_hex.c \
			src/ft_printf_utils/ft_handle/ft_handle_int.c \
			src/ft_printf_utils/ft_handle/ft_handle_int_u.c \
			src/ft_printf_utils/ft_handle/ft_handle_percentage.c \
			src/ft_printf_utils/ft_handle/ft_handle_ptr.c \
			src/ft_printf_utils/ft_handle/ft_handle_str.c \
			src/ft_printf_utils/ft_init/ft_conv_info_init.c \
			src/ft_printf_utils/ft_output/ft_conv_info_output.c \
			src/ft_printf_utils/ft_output/ft_output_char.c \
			src/ft_printf_utils/ft_output/ft_output_hex.c \
			src/ft_printf_utils/ft_output/ft_output_int.c \
			src/ft_printf_utils/ft_output/ft_output_percentage.c \
			src/ft_printf_utils/ft_output/ft_output_ptr.c \
			src/ft_printf_utils/ft_output/ft_output_str.c \
			src/ft_printf_utils/ft_output/ft_output_utils.c \
			src/ft_printf_utils/ft_set/ft_conv_info_set.c \
			src/ft_printf_utils/ft_set/ft_set_field_width.c \
			src/ft_printf_utils/ft_set/ft_set_flags.c \
			src/ft_printf_utils/ft_set/ft_set_precision.c \
			src/ft_printf_utils/ft_set/ft_set_specifier.c \
			src/ft_printf.c \
			src/ft_vprintf.c \
			src/ft_dprintf.c \
			src/ft_vdprintf.c \
			src/ft_getc.c \
			src/ft_getchar.c \
			src/ft_fgetc.c \
			src/ft_fwrite.c \
			src/ft_putchar.c \
			src/ft_fflush.c \
			src/ft_read.c \
			src/ft_write.c

# TEST	:=	test/ft_stdio_test.c
INCLUDE	:=	-Iinclude

# makeconfigを読み込む前にターゲットをinclude
include	../makeconfig
