# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kjikuhar <kjikuhar@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kjikuhar          #+#    #+#              #
#    Updated: 2025/10/15 15:26:55 by kjikuhar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_strings
SRC_FILES	:=	ft_bcmp.c \
				ft_bcopy.c \
				ft_bzero.c \
				ft_ffs.c \
				ft_index.c \
				ft_rindex.c \
				ft_strcasecmp.c \
				ft_strncasecmp.c
include	../makeconfig
