# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kjikuhar <kjikuhar@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/10/30 00:36:13 by kjikuhar          #+#    #+#              #
#    Updated: 2025/10/30 00:36:19 by kjikuhar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_ctype
SRC_FILES	:=	ft_get_ctype_table.c \
				ft_isalnum.c \
				ft_isascii.c \
				ft_iscntrl.c \
				ft_isgraph.c \
				ft_isprint.c \
				ft_isspace.c \
				ft_isxdigit.c \
				ft_toupper.c \
				ft_isalpha.c \
				ft_isblank.c \
				ft_isdigit.c \
				ft_islower.c \
				ft_ispunct.c \
				ft_isupper.c \
				ft_tolower.c
include	../makeconfig
