# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/16 17:25:27 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Variables
SUBDIR	:=	ft_stdlib
NAME	:=	ft_stdlib.a
SRC		:=	src/ft_abs.c \
			src/ft_labs.c \
			src/ft_llabs.c \
			src/ft_div.c \
			src/ft_ldiv.c \
			src/ft_lldiv.c \
			src/ft_itoa.c \
			src/ft_atoi.c \
			src/ft_atol.c \
			src/ft_atoll.c \
			src/ft_strtol.c \
			src/ft_strtoll.c \
			src/ft_strtoll_utils.c \
			src/ft_strtoul.c \
			src/ft_strtoull.c \
			src/ft_calloc.c

TESTDIR		:=	test
TEST		:=	$(TEST_DIR)/test.c
INCLUDE	+=	-Iinclude

include	../makeconfig
