# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kjikuhar <kjikuhar@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kjikuhar          #+#    #+#              #
#    Updated: 2025/10/15 15:26:55 by kjikuhar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_stdlib
SRC_FILES	:=	ft_abs.c \
				ft_labs.c \
				ft_llabs.c \
				ft_div.c \
				ft_ldiv.c \
				ft_lldiv.c \
				ft_itoa.c \
				ft_atoi.c \
				ft_atol.c \
				ft_atoll.c \
				ft_strtol.c \
				ft_strtoll.c \
				ft_strtoll_utils.c \
				ft_strtoul.c \
				ft_strtoull.c \
				ft_calloc.c
include		../makeconfig
