# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/14 12:26:41 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Variables
SUBDIR	:=	strings
NAME	:=	strings.a
SRC		:=	src/ft_bcmp.c \
			src/ft_bcopy.c \
			src/ft_bzero.c \
			src/ft_ffs.c \
			src/ft_index.c \
			src/ft_rindex.c \
			src/ft_strcasecmp.c \
			src/ft_strncasecmp.c

TEST	:=	test/ft_bcmp.c
INCLUDE	+=	-Iinclude

include	../makeconfig
