# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kjikuhar <kjikuhar@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/14 08:43:35 by kjikuhar          #+#    #+#              #
#    Updated: 2025/10/15 15:26:55 by kjikuhar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB_NAME	:=	ft_string
SRC_FILES	:=	ft_strchr.c \
				ft_strrchr.c \
				ft_strncmp.c \
				ft_strcpy.c \
				ft_strcat.c \
				ft_strlcpy.c \
				ft_strlcat.c \
				ft_strlen.c \
				ft_strdup.c \
				ft_strnstr.c \
				ft_substr.c \
				ft_strjoin.c \
				ft_strtrim.c \
				ft_strmapi.c \
				ft_striteri.c \
				ft_strrcmp.c \
				ft_free_split.c \
				ft_memset.c \
				ft_memcpy.c \
				ft_memmove.c \
				ft_memchr.c \
				ft_memcmp.c \
				ft_memrchr.c
include	../makeconfig
