# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/14 08:43:35 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/14 12:26:51 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


# Variables
SUBDIR	:=	ft_string
NAME	:=	ft_string.a
SRC		:=	src/ft_strchr.c \
			src/ft_strrchr.c \
			src/ft_strncmp.c \
			src/ft_strcpy.c \
			src/ft_strcat.c \
			src/ft_strlcpy.c \
			src/ft_strlcat.c \
			src/ft_strlen.c \
			src/ft_strdup.c \
			src/ft_strnstr.c \
			src/ft_substr.c \
			src/ft_strjoin.c \
			src/ft_strtrim.c \
			src/ft_strmapi.c \
			src/ft_striteri.c \
			src/ft_strrcmp.c \
			src/ft_free_split.c \
			src/ft_memset.c \
			src/ft_memcpy.c \
			src/ft_memmove.c \
			src/ft_memchr.c \
			src/ft_memcmp.c \
			src/ft_memrchr.c

# TEST	:=	ft_ctype_test.c
INCLUDE	+=	-Iinclude

include	../makeconfig
