# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kei2003730 <kei2003730@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/13 17:35:43 by kei2003730        #+#    #+#              #
#    Updated: 2025/07/13 19:43:46 by kei2003730       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


# **************************************************************************** #
# Makefile for ctype functions in libft
# **************************************************************************** #
# This Makefile is used to compile the ctype functions in the libft library.
# It includes the main libft Makefile and sets the subdirectory to 'ctype'.
# **************************************************************************** #
# Variables
SUBDIR := ctype
NAME := ctype.a
SRC  := src/ft_isalnum.c  src/ft_isascii.c  src/ft_iscntrl.c  src/ft_isgraph.c  src/ft_isprint.c  src/ft_isspace.c  src/ft_isxdigit.c  src/ft_toupper.c \
		src/ft_isalpha.c  src/ft_isblank.c  src/ft_isdigit.c  src/ft_islower.c  src/ft_ispunct.c  src/ft_isupper.c  src/ft_tolower.c
TEST := ft_ctype_test.c
INCLUDE += include
# Include the main Makefile
# **************************************************************************** #
# Targets
include ../makeconfig

# **************************************************************************** #
# End of Makefile for ctype functions in libft
# **************************************************************************** #
# This Makefile is part of the libft project and is used to manage the compilation
# of the ctype functions in the libft library.
# It defines the source files, object files, and the final library name.
# The targets include 'all' to build the library, 'clean' to remove object files,
# 'fclean' to remove the library, and 're' to rebuild everything.